{
	"version": 1733065882,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/bgbaru-sheet0.png",
		"images/mulairemovebgpreview-sheet0.png",
		"images/mulai__1_removebgpreview-sheet0.png",
		"images/bgbaru2-sheet0.png",
		"images/ceriremovebgpreview-sheet0.png",
		"images/desain_tanpa_judulremovebgpreview-sheet0.png",
		"images/beranda__1_removebgpreview-sheet0.png",
		"images/info__1_removebgpreview-sheet0.png",
		"images/papanremovebgpreview-sheet0.png",
		"images/kiri__1_removebgpreview-sheet0.png",
		"images/mulai__4_removebgpreview-sheet0.png",
		"images/kelaparemovebgpreview-sheet0.png",
		"images/jerukremovebgpreview-sheet0.png",
		"images/belimbingremovebgpreview-sheet0.png",
		"images/lemonremovebgpreview-sheet0.png",
		"images/delimaremovebgpreview-sheet0.png",
		"images/kurmaremovebgpreview-sheet0.png",
		"images/melonremovebgpreview-sheet0.png",
		"images/strawberryremovebgpreview-sheet0.png",
		"images/nanasremovebgpreview-sheet0.png",
		"images/pitaremovebgpreview-sheet0.png",
		"images/bintang1__1_removebgpreview-sheet0.png",
		"images/ulang__1_removebgpreview-sheet0.png",
		"images/beranda__1_removebgpreview2-sheet0.png",
		"images/smk-sheet0.png",
		"images/pplg-sheet0.png",
		"images/belajar-sheet0.png",
		"images/info__1_removebgpreview2-sheet0.png",
		"images/papanremovebgpreview2-sheet0.png",
		"images/ceriremovebgpreview2-sheet0.png",
		"images/kanan__1_removebgpreview-sheet0.png",
		"images/mulai__1_removebgpreview2-sheet0.png",
		"images/mulai__2_removebgpreview-sheet0.png",
		"images/mulai__3_removebgpreview-sheet0.png",
		"images/mulai__4_removebgpreview2-sheet0.png",
		"images/mulai__5_removebgpreview-sheet0.png",
		"images/mulai__6_removebgpreview-sheet0.png",
		"images/mulai__7_removebgpreview-sheet0.png",
		"images/mulai__8_removebgpreview-sheet0.png",
		"images/mulai__9_removebgpreview-sheet0.png",
		"images/mulairemovebgpreview2-sheet0.png",
		"media/utama (online-audio-converter.com).ogg",
		"media/benar (online-audio-converter.com).ogg",
		"media/salah (online-audio-converter.com).ogg",
		"media/akhir (online-audio-converter.com).ogg",
		"media/tombol (online-audio-converter.com).ogg",
		"media/subelimbing (online-audio-converter.com).ogg",
		"media/sumelon (online-audio-converter.com).ogg",
		"media/sudelima (online-audio-converter.com).ogg",
		"media/sujeruk (online-audio-converter.com).ogg",
		"media/sukelapa (online-audio-converter.com).ogg",
		"media/sukurma (online-audio-converter.com).ogg",
		"media/suleci (online-audio-converter.com).ogg",
		"media/sulemon (online-audio-converter.com).ogg",
		"media/sunanas (online-audio-converter.com).ogg",
		"media/sustrawberry (online-audio-converter.com).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}